### ISSUE TITLE
pinch on macbook pro too sensitive

### ISSUE THREAD

**Issue by mx2323** [prc5/react-zoom-pan-pinch#123]
has anyone else noticed that the pinch to zoom in / out is highly sensitive using the two finger pinch on macbook pros? 

it feels great on my mouse when im scrolling in and out with the mouse wheel, but something especially about the gesture on a macbook pro feels very twitchy and sensitive.

thoughts?

**Comment by alextouzel** [comment]
I'm having the same issue with a Windows 10 / Asus laptop and I had comments from users using different laptops, so I think it might not be related to Macbooks specifically.

When I use `wheel={{ step: 10 }}`, the zoom sensitivity makes sense on the touchpad, but is not enough sensitive with the mouse wheel. To have a proper mouse wheel zoom, I need to set the step aroudn 40, but then the touchpad is way too sensitive.

This is due to the number of times the "wheel" event is fired. When moving your mouse wheel, the event fires once every "wheel step", while it fires tens of times when moving a few millimetres on a touchpad. If this behavior is the same with every devices/browsers, we could adjust it by adding something like this to the `handleWheelZoom` method:

```
if (!event.ctrlKey) {
        step *= 4;
    }
```

But that would be a breaking change. Also I chose 4 as a factor because that makes sense for me, but it could be different. @prc5 what do you think?

**Comment by alextouzel** [comment]
I think a more viable solution would be to add a prop that controls specifically either the touchpad step or the wheel step.

@prc5 would you accept a PR that adds an optional `touchPadStep` prop? When not defined, both touchpad and wheel zooms would use the `step` value, so that wouldn't introduce a breaking change. It would solve this issue and give more control to developers using the library.
