### ISSUE TITLE
Is this package still being maintained?

### ISSUE THREAD

**Issue by Karhide** [prc5/react-zoom-pan-pinch#148]
Thanks to the authors for a great package. I think judging by the stars and issues list you have many loyal users. It'd be great to know how the community could help take up some of the slack.

Let us know!

**Comment by prc5** [comment]
Hey, it's very nice that you are offering to help maintain this library, I'd love to use any help. When creating it, I wanted to share something that was very necessary in the early project, but the assumptions have grown very much, so for example, we have so many animations in it. My minimum plan was to create a wrapper for previewing photos, which I suspect was successful. I will share with you the plans I had and which I still have, but I cannot implement them in the near future due to excess work.

**What is the goal?**
Create a tool not only for previewing photos, but give users more opportunities to create something similar to movement and the way it is done, known from the Miro application. With support for html, canvas etc.

**For this you need a few things:**
1. Most of the features are in place, now it would be time to clean up and optimize the library code
2. Improving how props are accepted and organized in the application (it's also a matter of architecture)
3. Support for prop "ref" to allow external access to the state library and methods
4. Correct velocity calculations for different zoom levels
5. Try to significantly increase the performance of the library
6. Implement full typescript support (in the beginning I created the library in pure js)
7. Automatic library tests

If anyone would like to help me in further development, please let me know. Thanks for such interest and commitment!

**Comment by Karhide** [comment]
Hey,

Thanks for replying! It's really a great package so I'd definitely be interested in helping out. I can't give a lot of time but I should be able to give some.

I think your vision sounds great. In order to learn the codebase the best way for me to start is probably to begin triaging issues and pull requests, if that's ok with you.

Hopefully others will come along too!

**Comment by prc5** [comment]
> Hey,
> 
> Thanks for replying! It's really a great package so I'd definitely be interested in helping out. I can't give a lot of time but I should be able to give some.
> 
> I think your vision sounds great. In order to learn the codebase the best way for me to start is probably to begin triaging issues and pull requests, if that's ok with you.
> 
> Hopefully others will come along too!

Sounds great, thanks!!

**Comment by OmkarRajam** [comment]
Hello @prc5,

Please review my PR #156. In the PR, I have added types that were missing which will be useful for the end-user. I believe that it is one of the goals that you have mentioned in this issue (improving typescript support).

Thank you in advance.

**Comment by prc5** [comment]
Some update from my side - as I started the project long time ago, I didn't really though it will get so much attention. I know I wasn't super active for more than year. I'm really glad that so many posted pull requests but the lib state itself wasn't good enough to iterate over this old codebase - so I managed to rewrite it to typescript, not like it was before. Now I need to clean up some stuff there, prepare docs, go through the issues and manage to fix what's left and close what's fixed. I've added some more features, fixed broken/bad logic, simplified it and boosted the performance. There will be proper typescript as I mentioned, everything got it's full types setup. I've moved from my custom docs page to the storybook - it will have much better usability I think, so it will be a good place to build the proper, interactive documentation. 

Version 2.0 will also make some changes to the props setup - better namings, less confusing props - and the best one - support for the ref - you will get the whole class reference there, as well as state and helpers etc. I hope you will like it :)
