### ISSUE TITLE
Incompatible with content security policy

### ISSUE THREAD

**Issue by krossekrabbe** [prc5/react-zoom-pan-pinch#240]
Hi, the dist files do contain a `styleInject` function which automatically writes the style tags to the html `<head>`. This is not working in conjunction with an active Content Security Policy. To make it work with CSP one would be required to allow `unsafe-inline` in the `style-src` directive.

One possible solution which is used by <a href="https://cssinjs.org/csp/?v=v10.0.0">JSS</a> afaik would be to look up if there's a csp-nonce meta tag in the page  (eg. `<meta property="csp-nonce" content="blablabla">`) and to use that information to add a `nonce` attribute to the injected `<style>` tag.

![Captura de pantalla de 2021-09-15 20-16-40](https://user-images.githubusercontent.com/313079/133487699-3bcc8fa4-a466-4cff-a0a6-28af2f65cad0.png)

Edit: I've just learned that functionality might come from rollup-plugin-postcss? Mh, then maybe it would be favourable to allow users to import the css separately, so they can chose themselves which loader they are using to process the css and how it's injected into the page.

**Comment by rmincling** [comment]
Hi,

We're currently coming up against this issue as well.

`
Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self' .....'". Either the 'unsafe-inline' keyword, a hash ....), or a nonce ('nonce-...') is required to enable inline execution.

styleInject  - index.esm.js
`
We've tried updating to latest version of react-zoom-pan-pinch but no change. Can anyone give advice how to get around this? Do we have to use rollup-plugin-postcss as mentioned above?

Regards,

**Comment by krossekrabbe** [comment]
Unfortunately I don't have a solution at hand, i guess I ended up using something different.

Also I don't remember why I closed the issue, maybe by accident when editing it 🤔🤔
