### ISSUE TITLE
Disable scroll on wheel for some cases

### ISSUE THREAD

**Issue by Taally** [prc5/react-zoom-pan-pinch#99]
Hello! In a TransformWrapper I have a react-select component with scrollable menu. But if wheel is enabled for TransformWrapper, I can't scroll the menu. It would be great if I had an opportunity to disable scroll depending on current target. (Or perhaps there is such opportunity and I don't know about it?)
Here is an example https://codesandbox.io/s/react-zoom-pan-pinch-ikikm

**Comment by proffesor888** [comment]
Hey, I'm having the same issue as @Taally with scroll..Inner Table component in not scrolling in Y axis. Is there any ways to achieve it ?

**Comment by JulStj** [comment]
What you can do is to have "wheelEnabled" stored as an outside variable that changes if the select have focus. And then in your TransformWrapper you have  
wheel={{ wheelEnabled: this.state.wheelEnabled }}

Or you just always have wheelEnabled: false all the time, because ctrl + wheel works for zooming inside TransformWrapper also

**Comment by Taally** [comment]
@JulStj oh, I will try that. Thank you!
